### ISSUE TITLE
`\rangle` error for inline LaTeX `#mi`

### ISSUE THREAD

**Issue by Yiyi-philosophy** [mitex-rs/mitex#169]
version: 0.2.4:
problem:
```
#mi("\langle{w_1}\rangle")
#mitex(`\langle{w_1}\rangle`)
```
is different, and #mi fail to generate \rangle.

by the way, could anyone tell me that how to present $\langle \rangle$ in typst?

**Comment by OrangeX4** [comment]
You shouldn't use double quotes "" because you need to deal with escapes.



---Original---
From: "Yiran ***@***.***&gt;
Date: Sun, Jun 2, 2024 15:58 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [mitex-rs/mitex] `\rangle` error for inline LaTeX `#mi` (Issue #169)




 
version: 0.2.4:
 problem:
 #mi("\langle{w_1}\rangle") #mitex(`\langle{w_1}\rangle`)  
is different, and #mi fail to generate \range.

**Comment by Yiyi-philosophy** [comment]
OK i see, thx
