### ISSUE TITLE
Space at the end of `\text` is not preserved

### ISSUE THREAD

**Issue by Enter-tainer** [mitex-rs/mitex#46]
```
#mitex(`
\text{A B C }D
`)
```
![image](https://github.com/OrangeX4/mitex/assets/25521218/21a39da4-9f6f-4b3f-a731-2d0116601bd3)

**Comment by Enter-tainer** [comment]
```
$text("A ")B$ #text("A ")B
```
![image](https://github.com/OrangeX4/mitex/assets/25521218/756273a9-49a9-412a-bce0-1c5dd4d1663f)

might be typst bug

**Comment by clvnkhr** [comment]
Hi, I looked a little into this, and want to share my findings in hopes that it helps (also in relation to https://github.com/mitex-rs/mitex/issues/128 where I quote `Currently we convert \text{ xxx } to " xxx " instead of [ xxx ], this is to keep the starting and ending spaces not ignored by typst. As a result of this decision, we can't actually get into text mode inside \text{} at the moment, and there may not be a good way to do it at the moment.`)

It turns out for spaces on the right, if you want a space between chars then the space has to be outside of the `#text(...)` (which is equivalent to `"..."`). Or you can use `#[...]`, then it doesn't matter where the space is. But there is a special case for single chars / single char followed by space e.g. `a `.  In this case you cannot use `#[...]`, only `"a " `(two spaces) works. `"a" ` does not. It seems that `a ` is used to escape the behavior of `a` as in https://github.com/typst/typst/issues/3732 , https://github.com/typst/typst/issues/274.
<img width="690" alt="Screenshot 2024-03-26 at 18 58 34" src="https://github.com/mitex-rs/mitex/assets/8646209/89e84475-383e-4111-b2d5-18696f2fd4d6">

For spaces on the left, its more or less the same, except that ` " a"`, ` " abc"` is a double space on the left. `#[...]` is more lenient, again except for single chars.
<img width="696" alt="Screenshot 2024-03-26 at 19 00 45" src="https://github.com/mitex-rs/mitex/assets/8646209/dc953ef6-f399-4feb-888b-fb23acb01f92">
With this in mind I wrote a small function that behaves more like LaTeX's `\text{...}`:
```typst
#let mytext(s) = {
  if type(s) != str {
    // allow passing in raw strings (e.g. `hello world`)
    s = s.text 
  }
  let st = s.trim(regex("\s+"))
  if st.len() == 0 {return s}
  if st == "" and s != "" {math.thick}
  else {
    if st.len() == 1 {st = st + " "}
    let lsp = if s.at(0) == " " {" "} else {}
    let rsp = if s.at(-1) == " " {" "} else {}
    [#lsp#st#rsp]
  }
}
```
In particular for https://github.com/mitex-rs/mitex/issues/128 this sort of logic should be good if switching to `#[...]` since there will be no nesting if there is only a single char in the `\text{...}`. But when I try e.g.
```typst
#eval(
  mitex-convert(`\text{extra space right of the "2"} \to $2\text{T}f$`),
  scope: ("textmath": mytext), mode: "math"
)
```
it doesn't work properly because apparently mitex adds a space after `2`.  This is kind of where I get stuck because I'm not sure what `textmath` is, and I don't know if this requires changes in the parser? 

Above pictures and code are from this typst doc: https://typst.app/project/rWe3DvF-m4yMXxAtl_ukUk

**Comment by OrangeX4** [comment]
Thanks for such a detailed test, I will find a way to solve this problem.
